---
title: "Introduction"
author: "Elodie Kwan and Katia Voltz"
date: '2022-04-26'
output: pdf_document
---


## Executive Summary

Data analysis is now a fundamental tool in the general understanding of business. In the current case, the objective would be to understand and profile the different historical and current customers of a bank, in order to better identify them. For this, we need to proceed in several steps: The first is to collect available data, check its relevance and see if it is accurate. Indeed, it is possible to deal with erroneous data. Therefore, it is necessary to verify each feature and instance collected. The second step is to clean and understand the data in order to proceed to a more complete analysis. Finally, the goal is to answer the problem by using different analytical methods and synthesising the best model to provide a solution. 


## Introduction 
In the bank industry many bankers have to decide whether or not they should issue a loan to a new coming applicant. In this report, we will use the data set called **German Credit data** which was given to us. 


The German credit data set contains 1000 observations of past credit applicants, described by 30 variables. The applicants are described as **Good Credit** risk or **Bad Credit** risk: Therefore, the response variable, studied, is the credit rating. 


Response variable: **RESPONSE** in the dataset:

+ 0 : Bad credit. In case of bad credit, the banker would not want to issue loan to this person. 
+ 1 : Good credit. In case of good credit, the banker will want to issue loan to this applicant as it is more likely that the company will benefit from it. 


All the other observations are features of the applicants that are going to be studied. It will allow us to perform several machine learning models and deploy a CRISP-DM model to come up with the best classifying model with the highest accuracy as possible. We want to determine whether the new applicant has a 'Good' credit risk, in which case the loan should be issued, or a 'Bad' credit risk, in which case it is not advisable to give him a loan.


The tasks required to perform our analysis is stated as follow. 

1/ We first proceeded to some data cleaning, meaning that we sorted the dataset to make it ready for the analysis. 

2/ Then we followed by an exploratory data analysis (EDA) where we studied the dataset and the different variables, one by one, and we made an principal component analysis. 

3/ Next, came the models analysis, the steps are listed below: 

  a) Splitting the dataset
  b) Balancing the data
  c) Fitting the models
  d) Accuracy study (scoring)
  e) Variable selection and importance
  f) Final Best model 
  
